# Generated by Django 3.2.7 on 2022-06-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['target_date']},
        ),
    ]
